version: "3"
services:
 web:
   build: .
   command: python py_kakeibo/manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 8000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: django
      MYSQL_USER: test
      MYSQL_PASSWORD: passwd
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3333:3306

volumes:
  db-data: